
VERSION = 1.0.3
QMAKE_TARGET_COMPANY = "JustCode"
QMAKE_TARGET_PRODUCT = "Resto"
QMAKE_TARGET_DESCRIPTION = "A small application for work time management"
QMAKE_TARGET_COPYRIGHT = $$QMAKE_TARGET_COMPANY

DEFINES += ORG_NAME='"\\\"$$QMAKE_TARGET_COMPANY\\\""'
DEFINES += ORG_DOMAIN=\\\"just-code.org\\\"
DEFINES += APP_NAME='"\\\"$$QMAKE_TARGET_PRODUCT\\\""'
DEFINES += APP_VERSION='"\\\"$$VERSION\\\""'
