name: build

on:
  workflow_call:
    inputs:
      create-package:
        type: boolean
        default: false
      build-type:
        required: true
        type: string
      qt-version:
        required: true
        type: string
      os:
        required: true
        type: string
    
env:
  linuxdeployqt-download-path: https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage
  QT_VERSION: ${{inputs.qt-version}}
  QT_COMPILER: ${{ inputs.os == 'linux' && 'gcc_64' || 'win64_msvc2019_64' }}
  QT_IFW_VERSION: 4.3
    
jobs:
  build_job:
    name: Build for ${{inputs.os}}
    runs-on: ${{ inputs.os == 'linux' && 'ubuntu' || 'windows' }}-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Install qt
      run: |
        pip install -U pip
        pip install aqtinstall
        aqt install-qt ${{inputs.os}} desktop ${{inputs.qt-version}} ${{env.QT_COMPILER}} --outputdir ${{github.workspace}}/qt
        
    - name: Install other dependencies (linux)
      if: ${{inputs.os == 'linux'}}
      run: |
        sudo apt-get update
        sudo apt-get install mesa-common-dev libglu1-mesa-dev
          
    - name: Configure CMake
      env:
        CMAKE_PREFIX_PATH: ${{github.workspace}}/qt/${{inputs.qt-version}}/${{ inputs.os == 'linux' && 'gcc_64' || 'msvc2019_64' }}/lib/cmake/
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{inputs.build-type}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{inputs.build-type}}
       
    - name: Install deploy dependencies (common)
      if: ${{inputs.create-package}}
      run: |
        QT_IFW_TOOL="${QT_IFW_VERSION//./}"
        aqt install-tool ${{inputs.os}} desktop tools_ifw qt.tools.ifw.${QT_IFW_TOOL}
        
    - name: Install deploy dependencies (linux)
      if: ${{inputs.create-package && inputs.os == 'linux'}}
      run: |
        wget https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage -P ${{github.workspace}}/qt/Tools/
          
    - name: Start a package script (linux)
      if: ${{inputs.create-package && inputs.os == 'linux'}}
      env:
        QT_PATH: ${{github.workspace}}/qt
      run: |
        sudo chmod +x ./scripts/desktop/${{inputs.os}}/create-package.sh
        echo "Running a script!"
        ./scripts/desktop/${{inputs.os}}/create-package.sh ${{github.workspace}}/build ${{github.workspace}}/packages
        ls ${{github.workspace}}/packages
