name: continuous

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  QT_VERSION: 5.15.2

jobs:
  build_linux:
    name: Build for linux
    runs-on: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v3

    - name: Install qt
      run: |
        pip install -U pip
        pip install aqtinstall
        aqt install-qt linux desktop ${{env.QT_VERSION}} gcc_64 --outputdir ${{github.workspace}}/qt
        
    - name: Install other dependencies
      run: |
        sudo apt-get update
        sudo apt-get install mesa-common-dev libglu1-mesa-dev
          
    - name: Configure CMake
      env:
        CMAKE_PREFIX_PATH: ${{github.workspace}}/qt/${{env.QT_VERSION}}/gcc_64/lib/cmake/
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      
  build_windows:
    name: Build for windows
    runs-on: [windows-latest]

    steps:
    - uses: actions/checkout@v3

    - name: Install qt
      run: |
        pip install -U pip
        pip install aqtinstall
        aqt install-qt windows desktop ${{env.QT_VERSION}} win64_msvc2019_64 --outputdir ${{github.workspace}}/qt
        dir ${{github.workspace}}/qt/${{env.QT_VERSION}}/
        
    - name: Configure CMake
      env:
        CMAKE_PREFIX_PATH: ${{github.workspace}}/qt/${{env.QT_VERSION}}/msvc2019_64/lib/cmake/
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      
