name: continuous

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

env:
  BUILD_TYPE: Release
  QT_VERSION: "5.15.2"

jobs:
  build-linux:
    uses: ./.github/workflows/build.yml
    with:
      build-type: $BUILD_TYPE
      qt-version: $QT_VERSION
      os: linux
      
  build_windows:
    uses: ./.github/workflows/build.yml
    with:
      build-type: $BUILD_TYPE
      qt-version: $QT_VERSION
      os: windows
