name: continuous

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

env:
  BUILD_TYPE: Release
  QT_VERSION: 5.15.2

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: ./.github/workflows/build.yml
      with:
        build-type: $${{env.BUILD_TYPE}}
        qt-version: $${{env.QT_VERSION}}
        os: linux
      
  build_windows:
    runs-on: windows-latest
    steps:
    - uses: ./.github/workflows/build.yml
      with:
        build-type: $${{env.BUILD_TYPE}}
        qt-version: $${{env.QT_VERSION}}
        os: windows
