name: continuous

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  env:
    BUILD_TYPE: Release
    QT_VERSION: 5.15.2

  build-linux:
    uses: ./.github/workflows/build.yml
    with:
      build-type: $${{env.BUILD_TYPE}}
      qt-version: $${{env.QT_VERSION}}
      os: linux
      
  build_windows:
    uses: ./.github/workflows/build.yml
    with:
      build-type: $${{env.BUILD_TYPE}}
      qt-version: $${{env.QT_VERSION}}
      os: windows
