name: continuous

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build-linux:
    uses: ./.github/workflows/build.yml
    with:
      build-type: Release   # TODO: find a way to avoid duplication
      qt-version: 5.15.2
      os: linux
      
  build-windows:
    uses: ./.github/workflows/build.yml
    with:
      build-type: Release   # TODO: find a way to avoid duplication
      qt-version: 5.15.2
      os: windows
