name: continuous

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  QT_VERSION: 5.15.2

jobs:
  build-linux:
    env:
      build-type: ${{env.BUILD_TYPE}}
      qt-version: ${{env.QT_VERSION}}
      
    uses: ./.github/workflows/build.yml
    with:
      build-type: ${{env.build-type}}
      qt-version: ${{env.qt-version}}
      os: linux
      
  build_windows:
    env:
      build-type: ${{env.BUILD_TYPE}}
      qt-version: ${{env.QT_VERSION}}
      
    uses: ./.github/workflows/build.yml
    with:
      build-type: ${{env.build-type}}
      qt-version: ${{env.qt-version}}
      os: windows
