name: delivery

on:
  push:
    branches: [ 'releases/**' ]
  pull_request:
    branches: [ master ]

jobs:
  build-linux:
    uses: ./.github/workflows/deploy.yml
    with:
      build-type: Release   # TODO: find a way to avoid duplication
      qt-version: 5.15.2
      os: linux
      
  build_windows:
    uses: ./.github/workflows/deploy.yml
    with:
      build-type: Release   # TODO: find a way to avoid duplication
      qt-version: 5.15.2
      os: windows
