name: delivery

on:
  push:
    branches: [ 'releases/**' ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build_linux:
    name: Build for linux
    runs-on: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      
  build_windows:
    name: Build for windows
    runs-on: [windows-latest]

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      
  delivery_linux:
    name: Delivery packages/instalers for linux
    runs-on: [ubuntu-latest]
    needs: build_linux

    steps:
    - name: Create delivery
      run: ./scripts/desktop/linux/create-delivery.sh ${{github.workspace}}/build ${{github.workspace}}/delivery
      
  delivery_windows:
    name: Delivery packages/instalers for winows
    runs-on: [windows-latest]
    needs: build_windows

    steps:
    - name: Create delivery
      run: ./scripts/desktop/windows/create-delivery.sh ${{github.workspace}}/build ${{github.workspace}}/delivery

      
