name: deploy

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
    
    
jobs:
  deploy-job:
    name: Package for ${{inputs.os}}
    runs-on: ${{ inputs.os == 'linux' && 'ubuntu' || 'windows' }}-latest
    
    steps:
    - name: Start a script
      run: |
        ./scripts/desktop/${{inputs.os}}/create-delivery.sh ${{github.workspace}}/build ${{github.workspace}}/packages
